version: '3.8'

services:
  db:
    image: mysql:latest
    env_file: ./.env
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "db", "-u", "root", "--password=$$MYSQL_ROOT_PASSWORD"]
      interval: 3s
      timeout: 3s
      retries: 15
      start_period: 20s
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - backend_data:/app/exposed/
    depends_on:
      db:
        condition: service_healthy
volumes:
  db_data:
  backend_data:
